# Generated by Django 2.2.16 on 2022-04-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(help_text='Оставьте свой комментарий', max_length=200, verbose_name='Текст комментария'),
        ),
    ]
